-- MySQL Script generated by MySQL Workbench
-- Sat Mar 11 11:25:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sis_comee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sis_comee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sis_comee` DEFAULT CHARACTER SET utf8mb3 ;
USE `sis_comee` ;

-- -----------------------------------------------------
-- Table `sis_comee`.`ramos_setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`ramos_setores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_ramo_setor` VARCHAR(45) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  `usuario_id_atualiza` INT(11) NULL DEFAULT NULL,
  `dt_ult_atualiza` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`fornecedores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_fornecedor` VARCHAR(200) NULL DEFAULT NULL,
  `nu_cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `nu_telefone` VARCHAR(17) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  `ramo_setor_id` INT(11) NOT NULL,
  `usuario_id_atualiza` INT(11) NULL DEFAULT NULL,
  `dt_ult_atualiza` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fornecedores_ramo_setor1_idx` (`ramo_setor_id` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedores_ramo_setor1`
    FOREIGN KEY (`ramo_setor_id`)
    REFERENCES `sis_comee`.`ramos_setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`funcionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`funcionalidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_funcionalidade` VARCHAR(45) NULL DEFAULT NULL,
  `in_menu` TINYINT(1) NULL DEFAULT NULL,
  `tx_url` VARCHAR(200) NULL DEFAULT NULL,
  `in_ativo` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`menus` (
  `id` INT(11) NOT NULL,
  `nm_menu` VARCHAR(45) NULL DEFAULT NULL,
  `nu_ordem` INT(11) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  `funcionalidade_id` INT(11) NOT NULL,
  `menu_id_pai` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menus_funcionalidades1_idx` (`funcionalidade_id` ASC) VISIBLE,
  INDEX `fk_menus_menus1_idx` (`menu_id_pai` ASC) VISIBLE,
  CONSTRAINT `fk_menus_funcionalidades1`
    FOREIGN KEY (`funcionalidade_id`)
    REFERENCES `sis_comee`.`funcionalidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_menus1`
    FOREIGN KEY (`menu_id_pai`)
    REFERENCES `sis_comee`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`perfis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_perfil` VARCHAR(45) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`perfis_funcionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`perfis_funcionalidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil_id` INT(11) NOT NULL,
  `funcionalidade_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfis_funcionalidades_perfis1_idx` (`perfil_id` ASC) VISIBLE,
  INDEX `fk_perfis_funcionalidades_funcionalidades1_idx` (`funcionalidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfis_funcionalidades_funcionalidades1`
    FOREIGN KEY (`funcionalidade_id`)
    REFERENCES `sis_comee`.`funcionalidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfis_funcionalidades_perfis1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `sis_comee`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_usuario` VARCHAR(100) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  `ds_email` VARCHAR(100) NULL DEFAULT NULL,
  `ds_login` VARCHAR(45) NULL DEFAULT NULL,
  `ds_senha` VARCHAR(255) NULL DEFAULT NULL,
  `usuario_id_atualiza` INT(11) NULL DEFAULT NULL,
  `dt_ult_atualiza` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`perfis_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`perfis_usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `usuario_id_atualiza` INT(11) NULL DEFAULT NULL,
  `dt_ult_atualiza` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfis_usuarios_perfis_idx` (`perfil_id` ASC) VISIBLE,
  INDEX `fk_perfis_usuarios_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfis_usuarios_perfis`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `sis_comee`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfis_usuarios_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sis_comee`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`tipos_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`tipos_produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_tipo_produto` VARCHAR(100) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  `usuario_id_atualiza` INT(11) NULL DEFAULT NULL,
  `dt_ult_atualiza` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_produto` VARCHAR(100) NULL DEFAULT NULL,
  `vl_produto` DECIMAL(5,2) NULL DEFAULT NULL,
  `tp_medida` VARCHAR(2) NULL DEFAULT NULL,
  `qtd_produto` INT(11) NULL DEFAULT NULL,
  `in_ativo` TINYINT(1) NULL DEFAULT NULL,
  `tipo_produto_id` INT(11) NOT NULL,
  `usuario_id_atualiza` INT(11) NULL DEFAULT NULL,
  `dt_ult_atualiza` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_tipos_produtos1_idx` (`tipo_produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_tipo_produto1`
    FOREIGN KEY (`tipo_produto_id`)
    REFERENCES `sis_comee`.`tipos_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sis_comee`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_categoria` VARCHAR(100) NULL,
  `in_ativo` TINYINT(1) NULL,
  `usuario_id_atualiza` INT(11) NULL,
  `dt_ult_atualiza` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_comee`.`fichas_tecnicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_comee`.`fichas_tecnicas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_ficha_tecnica` VARCHAR(200) NULL,
  `tempo_preparo` INT(11) NULL,
  `dt_criacao` DATETIME NULL,
  `dt_validade` DATETIME NULL,
  `ds_ingredientes` VARCHAR(200) NULL,
  `qtd_bruta` INT(11) NULL,
  `tx_desperdicio` INT(11) NULL,
  `qtd_liquida` INT(11) NULL,
  `ds_modo_preparo` VARCHAR(500) NULL,
  `ds_observacao` VARCHAR(200) NULL,
  `in_ativo` TINYINT(1) NULL,
  `usuario_id_atualiza` INT(11) NULL,
  `dt_ult_atualiza` DATETIME NULL,
  `tipo_produto_id` INT(11) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fichas_tecnicas_tipos_produtos1_idx` (`tipo_produto_id` ASC) VISIBLE,
  INDEX `fk_fichas_tecnicas_categorias1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_fichas_tecnicas_tipos_produtos1`
    FOREIGN KEY (`tipo_produto_id`)
    REFERENCES `sis_comee`.`tipos_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fichas_tecnicas_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `sis_comee`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
